# action.yml
name: 'Vault Client'
description: 'Actions wrapper for the HashiCorp Vault CLI'
inputs:
  addr:
    description: 'Vault URL'
    required: true
    default: 'https://localhost:8200'
  auth_method:
    required: true
    description: 'Method to authenticate with'
    default: 'token'
  secrets:
    required: true
    description: 'List of secrets'
  role:
    required: false
    description: 'Role to authenticate'
  username:
    required: false
    description: 'LDAP username'
  password:
    required: false
    description: 'LDAP password'
  token:
    required: false
    description: 'Token for authentication'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -a ${{ inputs.addr }}
    - -m ${{ inputs.auth_method }}
    - -t ${{ inputs.token }}
    - -r ${{ inputs.role }}
    - -u ${{ inputs.username }}
    - -p ${{ inputs.password }}
    - -s ${{ inputs.secrets }}
