# action.yml
name: 'Vault Client'
description: 'Actions wrapper for the HashiCorp Vault CLI'
inputs:
  addr:
    description: 'Vault URL'
    required: true
    default: 'https://localhost:8200'
  auth_method:
    required: true
    description: 'Method to authenticate with'
    default: 'token'
  secrets:
    required: true
    description: 'List of secrets'
  role:
    required: false
    description: 'Role to authenticate'
  username:
    required: false
    description: 'LDAP username'
  password:
    required: false
    description: 'LDAP password'
  token:
    required: false
    description: 'Token for authentication'
outputs:
  vault_addr_out:
    description: 'Vault URL'
  auth_method_out:
    description: 'Method to authenticate with'
  role_out:
    description: 'Role to authenticate'
  username_out:
    description: 'LDAP username'
  password_out:
    description: 'LDAP passsword'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --addr ${{ inputs.addr }}
    - --auth_method ${{ inputs.auth_method }}
    - --token ${{ inputs.token }}
    - --role ${{ inputs.role }}
    - --username ${{ inputs.username }}
    - --password ${{ inputs.password }}
    - --secrets ${{ inputs.secrets }}
