FROM alpine:3.10

ENV VAULT_VERSION 1.5.4

RUN wget --quiet https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip &&\
    unzip vault_${VAULT_VERSION}_linux_amd64.zip &&\
    rm vault_${VAULT_VERSION}_linux_amd64.zip &&\
    mv vault /usr/local/bin/vault

RUN apk add bash

COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
